Fix checking Android platform with __ANDROID__ macro
This change fixes compiler errors in Android as following.

../../../iodev/sound/soundoss.cc:43:10: fatal error: 'sys/soundcard.h' file not found
   43 | #include <sys/soundcard.h>
      |          ^~~~~~~~~~~~~~~~~
../../../iodev/network/slirp/misc.cc:195:12: error: use of undeclared identifier 'getdtablesize'; did you mean 'getpagesize'?
  195 |                 for (s = getdtablesize() - 1; s >= 3; s--)
      |                          ^~~~~~~~~~~~~
      |                          getpagesize
/data/data/com.termux/files/usr/include/unistd.h:356:5: note: 'getpagesize' declared here
  356 | int getpagesize(void) __INTRODUCED_IN(21);
      |     ^

The official documentation also suggests to use __ANDROID__ macro which
is defined by the compiler irrespective of included headers and build system.
https://android.googlesource.com/platform/bionic/+/HEAD/docs/defines.md